FROM nginx:alpine
# No Dockerfile do front basicamente copio todas as páginas html para a pasta /usr/share/nginx/html/ e o nginx.conf também
COPY ./*.html /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/nginx.conf